//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VInspectionWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListSummary
    {
        public int IdResumen { get; set; }
        public string Vehiculo { get; set; }
        public string Conductor { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Kilometraje { get; set; }
        public string Produccion { get; set; }
        public string Destino { get; set; }
        public string MensajeMantto { get; set; }
        public string Items1 { get; set; }
        public string Items2 { get; set; }
        public string Comentarios1 { get; set; }
        public string Comentarios2 { get; set; }
        public string Botiquin1 { get; set; }
        public string Botiquin2 { get; set; }
        public string Botiquin3 { get; set; }
        public string Seguridad1 { get; set; }
        public string Seguridad2 { get; set; }
        public string Seguridad3 { get; set; }
        public string Seguridad4 { get; set; }
        public int BanderaMantto { get; set; }
        public int BanderaItems { get; set; }
        public int BanderaComentarios { get; set; }
        public int BanderaBotiquin { get; set; }
        public int BanderaDocumentos { get; set; }
        public int BanderaPrincipal { get; set; }
        public int BanderaMensajes { get; set; }
        public string ComentariosVigilancia { get; set; }
        public string Buscador { get; set; }
        public string Garitas { get; set; }
        public int Estado { get; set; }
    }
}
