//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VInspectionWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckList
    {
        public int IdPreUso { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Placa { get; set; }
        public double Kilometraje { get; set; }
        public string Mantto { get; set; }
        public string Produccion { get; set; }
        public string Destino { get; set; }
        public string Conductor { get; set; }
        public string SistemaDireccion { get; set; }
        public string SistemaFrenos { get; set; }
        public string Faros { get; set; }
        public string LucesDireccionales { get; set; }
        public string Asientos { get; set; }
        public string Cinturones { get; set; }
        public string Vidrios { get; set; }
        public string LimpiaParabrisas { get; set; }
        public string EspejoInterno { get; set; }
        public string EspejoExterno { get; set; }
        public string NivelAceite { get; set; }
        public string NivelAgua { get; set; }
        public string Combustible { get; set; }
        public string Claxon { get; set; }
        public string AlarmaRetorceso { get; set; }
        public string RelojesIndicadores { get; set; }
        public string Neumaticos { get; set; }
        public string NeumaticoRepuesto { get; set; }
        public string Extintor { get; set; }
        public string ConosSeguridad { get; set; }
        public string SogaArrastre { get; set; }
        public string Botiquin { get; set; }
        public string HerramientasLlaves { get; set; }
        public string GataPalanca { get; set; }
        public string Triangulo { get; set; }
        public string Linterna { get; set; }
        public string Cunas { get; set; }
        public string Carroceria { get; set; }
        public string Pertiga { get; set; }
        public string Circulina { get; set; }
        public string ComentariosAdicionales { get; set; }
        public string Observacion1 { get; set; }
        public Nullable<int> Prioridad1 { get; set; }
        public string Observacion2 { get; set; }
        public Nullable<int> Prioridad2 { get; set; }
        public string Observacion3 { get; set; }
        public Nullable<int> Prioridad3 { get; set; }
        public string Observacion4 { get; set; }
        public Nullable<int> Prioridad4 { get; set; }
        public string CajaSoporte { get; set; }
        public string Alcohol { get; set; }
        public string Jabon { get; set; }
        public string Algodon { get; set; }
        public string Aposito { get; set; }
        public string Bandas { get; set; }
        public string Esparadrapo { get; set; }
        public string Gasas1 { get; set; }
        public string Gasas2 { get; set; }
        public string Tijera { get; set; }
        public string Venda { get; set; }
        public string ComentariosBotiquin { get; set; }
        public string EstadoSOAT { get; set; }
        public Nullable<System.DateTime> NuevaFechaSOAT { get; set; }
        public string EstadRevTecnica { get; set; }
        public Nullable<System.DateTime> NuevaFechaRevTecnica { get; set; }
        public string SOAT { get; set; }
        public string RevTecnica { get; set; }
        public string TarjetaPropiedad { get; set; }
        public string CartillaSeguridad { get; set; }
        public string CartillaERP { get; set; }
        public int BanderaMantto { get; set; }
        public int BanderaItems { get; set; }
        public int BanderaComentarios { get; set; }
        public int BanderaBotiquin { get; set; }
        public int BanderaDocumentos { get; set; }
        public int BanderaPrincipal { get; set; }
        public string Buscador { get; set; }
        public string Garitas { get; set; }
    }
}
