//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VInspectionWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Cuenta { get; set; }
        public string Contrasena { get; set; }
        public string Perfil { get; set; }
        public string Area { get; set; }
        public string Buscador { get; set; }
    }
}
