//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VInspectionWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int IdVehiculo { get; set; }
        public string Placa { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Responsable { get; set; }
        public string Area { get; set; }
        public string Encargado { get; set; }
        public double KUMantto { get; set; }
        public System.DateTime FUMantto { get; set; }
        public double Kilometraje { get; set; }
        public string Central { get; set; }
        public int Estado { get; set; }
        public string Buscador { get; set; }
    }
}
